name: dockerize tools

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dockerized-tools.yml'
      - 'dockerized-tools/**'
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log into registry
        run: echo ${{secrets.DOCKER_REGISTRY_PASSWORD}} | docker login -u vjcubas --password-stdin

      - name: Build and push the images
        run: |
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "Dockerfile");
          do
            folder=${versionFilePath%"/Dockerfile"}
            IMAGE_NAME=${folder##*/}

            # tmpName="image-$RANDOM"
            # docker build $folder --file $folder/Dockerfile --tag $tmpName
            # IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.REPOSITORY }}/$IMAGE_NAME
            # VERSION=$(cat $versionFilePath)

            # echo IMAGE_ID=$IMAGE_ID
            # echo VERSION=$VERSION

            # docker tag $tmpName $IMAGE_ID:$VERSION
            # docker push $IMAGE_ID:$VERSION
            echo $folder
            echo $IMAGE_NAME
          done;



