name: Dockerized tools
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push changes
      uses: harrygogonis/docker-monorepo-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


