name: GitHub Context

on:
  push:
    branches: [ "main" ]

jobs:
  dump:
    name: Dump github object attributes
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"